name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v3

    - name: Build
      run: cargo build --release --verbose && ls -lha /home/runner/work/sonic/sonic/target/release
    
    - name: Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: sonic-server
        path: |
          /home/runner/work/sonic/sonic/target/release
